from distutils.core import setup

setup(
    name='collectors',
    version='1.0',
    packages=['learn_python', 'learn_python.test', 'learn_python.lixiong', 'learn_python.lixiong.learn_io',
              'learn_python.lixiong.learn_iter', 'learn_python.lixiong.learn_flask',
              'learn_python.lixiong.learn_flask.study', 'learn_python.lixiong.learn_flask.study.hook',
              'learn_python.lixiong.learn_flask.study.abort', 'learn_python.lixiong.learn_flask.study.flash',
              'learn_python.lixiong.learn_flask.study.flash.templates', 'learn_python.lixiong.learn_flask.study.macro',
              'learn_python.lixiong.learn_flask.study.macro.templates', 'learn_python.lixiong.learn_flask.study.mysql',
              'learn_python.lixiong.learn_flask.study.cookie', 'learn_python.lixiong.learn_flask.study.static',
              'learn_python.lixiong.learn_flask.study.session', 'learn_python.lixiong.learn_flask.study.template',
              'learn_python.lixiong.learn_flask.study.template.templates',
              'learn_python.lixiong.learn_flask.study.exception', 'learn_python.lixiong.learn_flask.study.flask_mail',
              'learn_python.lixiong.learn_flask.study.development',
              'learn_python.lixiong.learn_flask.study.request_obj',
              'learn_python.lixiong.learn_flask.study.flask_script',
              'learn_python.lixiong.learn_flask.study.response_obj',
              'learn_python.lixiong.learn_flask.study.flask_migrate',
              'learn_python.lixiong.learn_flask.study.json_response',
              'learn_python.lixiong.learn_flask.study.flask_blueprint',
              'learn_python.lixiong.learn_flask.study.flask_blueprint.templates',
              'learn_python.lixiong.learn_flask.study.flask_blueprint.blueprint001',
              'learn_python.lixiong.learn_flask.study.flask_blueprint.blueprint002',
              'learn_python.lixiong.learn_flask.study.flask_blueprint.blueprint003',
              'learn_python.lixiong.learn_flask.study.request_content',
              'learn_python.lixiong.learn_flask.study.wtf_form_script',
              'learn_python.lixiong.learn_flask.study.wtf_form_script.templates', 'learn_python.lixiong.learn_magic',
              'learn_python.lixiong.learn_mysql', 'learn_python.lixiong.learn_yield',
              'learn_python.lixiong.learn_celery', 'learn_python.lixiong.learn_celery.tasks',
              'learn_python.lixiong.learn_celery.project', 'learn_python.lixiong.learn_celery.get_start',
              'learn_python.lixiong.learn_pandas', 'learn_python.lixiong.learn_pandas.learn_merge',
              'learn_python.lixiong.learn_logging', 'learn_python.lixiong.learn_logging.context_manager',
              'learn_python.lixiong.learn_logging.learn_level_use',
              'learn_python.lixiong.learn_logging.learn_level_use.task',
              'learn_python.lixiong.learn_logging.learn_level_use.view',
              'learn_python.lixiong.learn_logging.learn_level_use.report',
              'learn_python.lixiong.learn_logging.buffering_logger',
              'learn_python.lixiong.learn_logging.speeking_message',
              'learn_python.lixiong.learn_logging.learn_source_code',
              'learn_python.lixiong.learn_logging.rotater_customize',
              'learn_python.lixiong.learn_logging.config_logging_from_file',
              'learn_python.lixiong.learn_logging.configuration_server_example',
              'learn_python.lixiong.learn_logging.customize_exception_formattor',
              'learn_python.lixiong.learn_logging.customize_filter_pass_argument',
              'learn_python.lixiong.learn_logging.multiple_modules_using_logging',
              'learn_python.lixiong.learn_logging.multiple_threads_using_logging',
              'learn_python.lixiong.learn_logging.customize_handler_pass_argument',
              'learn_python.lixiong.learn_logging.dealing_with_handlers_that_block',
              'learn_python.lixiong.learn_logging.logging_to_multiple_destinations',
              'learn_python.lixiong.learn_logging.multiple_handlers_and_formatters',
              'learn_python.lixiong.learn_logging.elaborate_multiprocessing_example',
              'learn_python.lixiong.learn_logging.subclassing_queuehandler_a_zeromq',
              'learn_python.lixiong.learn_logging.using_filter_to_impart_contextual_information',
              'learn_python.lixiong.learn_logging.adding_contextual_information_to_logging_output',
              'learn_python.lixiong.learn_logging.sending_and_receiving_logging_events_from_socket',
              'learn_python.lixiong.download_b_web', 'learn_python.lixiong.learn_argparse',
              'learn_python.lixiong.learn_net_code', 'learn_python.lixiong.learn_rabbitmq',
              'learn_python.lixiong.learn_rabbitmq.learn_rpc', 'learn_python.lixiong.learn_coroutine',
              'learn_python.lixiong.type_programmer', 'learn_python.lixiong.learn_concurrent',
              'learn_python.lixiong.learn_concurrent.practice', 'learn_python.lixiong.learn_mutil_thread',
              'learn_python.lixiong.learn_mutil_process', 'learn_python.lixiong.learn_thread_second',
              'learn_python.lixiong.learn_design_pattern', 'learn_python.lixiong.learn_design_pattern.creator_pattern',
              'learn_python.lixiong.learn_design_pattern.factory_pattern',
              'learn_python.lixiong.learn_design_pattern.learn_proxy_pattern',
              'learn_python.lixiong.learn_design_pattern.learn_five_principle',
              'learn_python.lixiong.learn_design_pattern.learn_command_pattern',
              'learn_python.lixiong.learn_design_pattern.learn_mediator_pattern',
              'learn_python.lixiong.learn_design_pattern.learn_strategy_pattern',
              'learn_python.lixiong.learn_design_pattern.learn_prototype_pattern',
              'learn_python.lixiong.learn_design_pattern.learn_responsibility_pattern'],
    url='',
    license='',
    author='zzlion',
    author_email='',
    description=''
)
